version: '3'
services:
  ui:
    build:
      context: ./ui
    depends_on:
      - db
    ports:
      - '8001:8001'
    volumes:
      - ./ui:/app
    environment:
      DATABASE_NAME: gastly
      DATABASE_USER: gastly
      DATABASE_PASSWORD: gastly-pw
      DATABASE_HOST: db

  db:
    image: mysql
    volumes:
      - 'mysql:/var/lib/mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gastly
      MYSQL_USER: gastly
      MYSQL_PASSWORD: gastly-pw

volumes:
  mysql:
