version: '3'
services:
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - '8001:8001'
    volumes:
      - ./backend:/app
    environment:
      DATABASE_NAME: gastly
      DATABASE_USER: gastly
      DATABASE_PASSWORD: gastly-pw
      DATABASE_HOST: db

  ui:
    build:
      context: ./ui
    ports:
      - '8081:8080'
    volumes:
      - ./ui:/app

  db:
    image: mysql
    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - '3316:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gastly
      MYSQL_USER: gastly
      MYSQL_PASSWORD: gastly-pw

volumes:
  mysql:
