# Generated by Django 2.0.6 on 2018-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=256)),
                ('database', models.CharField(max_length=256)),
                ('table', models.CharField(max_length=256)),
                ('alter_statement', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('copy_percentage', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
